name: TSFX Release Pipeline

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/check-version.yml
    with:
      packages_matrix: '["core"]'

  publish:
    needs: check
    uses: ./.github/workflows/publish.yml
    with:
      packages_matrix: '["core"]'
      packages_to_release: ${{ needs.check.outputs.packages_to_release }}

  release:
    needs: [check, publish]
    if: needs.check.outputs.packages_to_release != ''
    uses: ./.github/workflows/release.yml